#page title
page_title                                : Netliphy                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1559050579                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/us/app/netliphy/id1559050579                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Netliphy                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Netliphy is designed to make it easy to manage your Netlify hosted sites using your iPhone or iPad!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Lisin Dmitriy                                
your_link                                 : https://lisindmitriy.me                     
your_city                                 : Barnaul                                
email_address                             : me@lisindmitriy.me
facebook_username                         : lisindmitriy                                      
instagram_username                        : lisindima
twitter_username                          : lisindima
github_username                           : lisindima
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : List of sites
    description                           : View a list of your sites and your teams.
    fontawesome_icon_name                 : list
    
  - title                                 : Monitor your deployments
    description                           : You can control the deployment of your sites using logs.
    fontawesome_icon_name                 : star

  - title                                 : Site settings
    description                           : View the settings of your sites.
    fontawesome_icon_name                 : cog

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0
topbar_title_color                        : "#000"

cover_image                               : #assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000"

link_color                                : "#FFF9B0"

app_title_color                           : "#fff"
app_price_color                           : "#fff"
app_description_color                     : "#fff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#FFF9B0"
feature_icons_background_color            : "#222"

social_icons_foreground_color             : "#FFF9B0"
social_icons_background_color             : "#222"

footer_text_color                         : "#fff"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown